rails g active_admin:resource  Team
rails g active_admin:resource  Member
rails g active_admin:resource  SimpleQuestion
rails g active_admin:resource  SimpleQuestionAlternative
rails g active_admin:resource  GroupQuestion
rails g active_admin:resource  GroupQuestionStatement
rails g active_admin:resource  GroupQuestionAlternative
rails g active_admin:resource  Company
rails g active_admin:resource  Test
rails g active_admin:resource  TestType
rails g active_admin:resource  TestGuideBasic
